# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Wtyczka_KS_VP
                                 A QGIS plugin
 Wtyczka, która liczy rożnicę wysokości i pole powierzchni.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-09
        copyright            : (C) 2023 by KS_VP
        email                : VPanchuk3005.02@ukr.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Wtyczka_KS_VP class from file Wtyczka_KS_VP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Wtyczka_KS_VP import Wtyczka_KS_VP
    return Wtyczka_KS_VP(iface)
