# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wtyczka_KS_VP_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 427)
        self.calculateHeightButton = QtWidgets.QPushButton(Dialog)
        self.calculateHeightButton.setGeometry(QtCore.QRect(350, 80, 121, 31))
        self.calculateHeightButton.setObjectName("calculateHeightButton")
        self.WysokoscWynik = QtWidgets.QLabel(Dialog)
        self.WysokoscWynik.setGeometry(QtCore.QRect(120, 110, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.WysokoscWynik.setFont(font)
        self.WysokoscWynik.setObjectName("WysokoscWynik")
        self.PoleButton = QtWidgets.QPushButton(Dialog)
        self.PoleButton.setGeometry(QtCore.QRect(360, 240, 111, 31))
        self.PoleButton.setObjectName("PoleButton")
        self.PoleWynik = QtWidgets.QLabel(Dialog)
        self.PoleWynik.setGeometry(QtCore.QRect(130, 280, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PoleWynik.setFont(font)
        self.PoleWynik.setObjectName("PoleWynik")
        self.WyborWarstwyComboBox = QgsMapLayerComboBox(Dialog)
        self.WyborWarstwyComboBox.setGeometry(QtCore.QRect(120, 30, 351, 41))
        self.WyborWarstwyComboBox.setObjectName("WyborWarstwyComboBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.calculateHeightButton.setText(_translate("Dialog", "Oblicz wysokość"))
        self.WysokoscWynik.setText(_translate("Dialog", "Wysokość punktu:"))
        self.PoleButton.setText(_translate("Dialog", "Oblicz pole"))
        self.PoleWynik.setText(_translate("Dialog", "Pole:"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
