# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Wtyczka_KS_VPDialog
                                 A QGIS plugin
 Wtyczka, która liczy różnicę wysokości i pole powierzchni.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-09
        git sha              : $Format:%H$
        copyright            : (C) 2023 by KS_VP
        email                : VPanchuk3005.02@ukr.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsGeometry
from qgis.core import QgsProject, QgsDistanceArea, QgsCoordinateReferenceSystem


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Wtyczka_KS_VP_dialog_base.ui'))


class Wtyczka_KS_VPDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Wtyczka_KS_VPDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.calculateHeightButton.clicked.connect(self.roznica_wysokosci)
        self.PoleButton.clicked.connect(self.pole)

        # Utwórz listę warstw i ustaw ją jako opcje w ComboBox
        self.warstwy = QgsProject.instance().mapLayers().values()
        for warstwa in self.warstwy:
            self.WyborWarstwyComboBox.addItem(warstwa.name())

    def roznica_wysokosci(self):
        wybrana_warstwa = self.WyborWarstwyComboBox.currentText()

        # Znajdź warstwę o wybranej nazwie
        warstwa = None
        for warstwa_ in self.warstwy:
            if warstwa_.name() == wybrana_warstwa:
                warstwa = warstwa_
                break

        if warstwa is None:
            self.WysokoscWynik.setText("Warstwa o podanej nazwie nie istnieje.")
            return

        # Sprawdź, czy dokonano wyboru 2 punktów na warstwie
        punkty = warstwa.selectedFeatures()
        if len(punkty) != 2:
            self.WysokoscWynik.setText("Wybierz 2 punkty na warstwie.")
            return

        # Oblicz różnicę wysokości
        pkt1 = punkty[0]
        pkt2 = punkty[1]
        wysokosc1 = pkt1.attribute("zcoord")
        wysokosc2 = pkt2.attribute("zcoord")
        roznica = wysokosc1 - wysokosc2

        self.WysokoscWynik.setText(
            f"Różnica wysokości między punktami {', '.join(str(pkt.id()) for pkt in punkty)} wynosi: {roznica} m")
        #Różnica wysokości między punktami o numerachPKT1,PKT2wynosi:WYNIK[m]”);
        

# ...

    def pole(self):
        wybrana_warstwa = self.WyborWarstwyComboBox.currentText()

        # Znajdź warstwę o wybranej nazwie
        warstwa = None
        for warstwa_ in self.warstwy:
            if warstwa_.name() == wybrana_warstwa:
                warstwa = warstwa_
                break

        if warstwa is None:
            self.PoleWynik.setText("Warstwa o podanej nazwie nie istnieje.")
            return

        # Sprawdź, czy dokonano wyboru co najmniej 3 punktów na warstwie
        punkty = warstwa.selectedFeatures()
        if len(punkty) < 3:
            self.PoleWynik.setText("Wybierz co najmniej 3 punkty na warstwie.")
            return

        # Utwórz listę punktów geometrycznych
        punkty_pkt = [pkt.geometry().asPoint() for pkt in punkty]

        # Utwórz polygon geometry
        geometry = QgsGeometry.fromPolygonXY([punkty_pkt])

        # Oblicz pole powierzchni
        area = geometry.area()

        self.PoleWynik.setText(
            f"Pole powierzchni {', '.join(str(pkt.id()) for pkt in punkty)} wynosi: {area} m^2")
        pkt1 = punkty[0]
        pkt2 = punkty[1]
        pkt3 = punkty[2]
        pole_pkt = QgsDistanceArea()
        pole_pkt.setSourceCrs(QgsCoordinateReferenceSystem('EPSG:4326'), QgsProject.instance().crs().authid())
        pole_pkt.ellipsoidalMode = True  # Ustawienie trybu elipsoidalnego na True

        punkty_pkt = [pkt1.geometry().asPoint(), pkt2.geometry().asPoint(), pkt3.geometry().asPoint()]
        pole = pole_pkt.measurePolygon(punkty_pkt)

        self.PoleWynik.setText(
            f"Pole wynosi: {pole} [m^2]")
#####

