# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wtyczka_KS_VP_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 427)
        self.WyborWarstwyComboBox = QtWidgets.QComboBox(Dialog)
        self.WyborWarstwyComboBox.setGeometry(QtCore.QRect(120, 30, 351, 41))
        self.WyborWarstwyComboBox.setObjectName("WyborWarstwyComboBox")
        self.calculateHeightButton = QtWidgets.QPushButton(Dialog)
        self.calculateHeightButton.setGeometry(QtCore.QRect(370, 80, 101, 31))
        self.calculateHeightButton.setObjectName("calculateHeightButton")
        self.WysokoscWynik = QtWidgets.QLabel(Dialog)
        self.WysokoscWynik.setGeometry(QtCore.QRect(160, 110, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WysokoscWynik.setFont(font)
        self.WysokoscWynik.setObjectName("WysokoscWynik")
        self.ZaznaczonePunkty = QtWidgets.QCheckBox(Dialog)
        self.ZaznaczonePunkty.setGeometry(QtCore.QRect(130, 200, 131, 31))
        self.ZaznaczonePunkty.setObjectName("ZaznaczonePunkty")
        self.PoleButton = QtWidgets.QPushButton(Dialog)
        self.PoleButton.setGeometry(QtCore.QRect(370, 240, 101, 31))
        self.PoleButton.setObjectName("PoleButton")
        self.PoleWynik = QtWidgets.QLabel(Dialog)
        self.PoleWynik.setGeometry(QtCore.QRect(170, 290, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PoleWynik.setFont(font)
        self.PoleWynik.setObjectName("PoleWynik")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.calculateHeightButton.setText(_translate("Dialog", "PushButton"))
        self.WysokoscWynik.setText(_translate("Dialog", "Wysokość punktu:"))
        self.ZaznaczonePunkty.setText(_translate("Dialog", "CheckBox"))
        self.PoleButton.setText(_translate("Dialog", "PushButton"))
        self.PoleWynik.setText(_translate("Dialog", "Wysokość punktu:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
